spring.application.name=carrental-system
spring.datasource.url=jdbc:mysql://localhost:3306/car_rental_db?zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.username=root
spring.datasource.password=Maxtony8625

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Data initialization
spring.sql.init.mode=never

server.port=8080

# JWT Configuration
jwt.secret=your-secret-key-change-this-in-production
jwt.expiration=86400000

# File Upload
file.upload-dir=uploads/

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eslimoses2005@gmail.com
spring.mail.password=lceslgfqoqjrlpsu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Twilio Configuration
twilio.account.sid=ACcf752e10a72ec61f916b919edbded23b
twilio.auth.token=b427ac97700d2b2cf047b9bc2f90ccb9
twilio.whatsapp.from=whatsapp:+14155238886